[package]
name = "koshkasock"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tracing = "0.1.40"
log = "0.4"
env_logger = "0.9"
csv = "1.1"
sha2 = "0.9"
